'use strict';
const r = require('express').Router();
const c = require('../controllers/alert.controller');
const { protect, restrict } = require('../middleware/auth.middleware');
r.use(protect);
r.get('/',              c.list);
r.get('/unread-count',  c.unreadCount);
r.get('/:id',           c.getById);
r.patch('/read-all',    c.markAllRead);
r.patch('/:id/read',    c.markRead);
r.patch('/:id/resolve', restrict('admin','analyst'), c.resolve);
r.delete('/:id',        restrict('admin'), c.remove);
module.exports = r;
