'use strict';
const r = require('express').Router();
const c = require('../controllers/analytics.controller');
const { protect } = require('../middleware/auth.middleware');
r.use(protect);
r.get('/overview',          c.overview);
r.get('/trend',             c.trend);
r.get('/country-heatmap',   c.countryHeatmap);
r.get('/device-breakdown',  c.deviceBreakdown);
r.get('/type-breakdown',    c.typeBreakdown);
r.get('/top-signals',       c.topSignals);
r.get('/risk-distribution', c.riskDistribution);
module.exports = r;
