'use strict';
const r = require('express').Router();
const c = require('../controllers/user.controller');
const { protect, restrict } = require('../middleware/auth.middleware');
r.use(protect, restrict('admin'));
r.get('/',      c.list);
r.get('/:id',   c.getById);
r.patch('/:id', c.update);
r.delete('/:id', c.remove);
module.exports = r;
